### ISSUE TITLE
govuk_template_jinja isn't up-to-date

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_template_jinja#1]
This repo should have been updated 0.18.3, to match the [govuk_template](https://github.com/alphagov/govuk_template).

**Comment by selfthinker** [comment]
Fixed. See https://github.com/alphagov/govuk_template_jinja/releases/tag/v0.18.3

The issue was that a recent change in GitHub permissions left the "govuk-ci" user without permissions for this repository. And the CI needs that permission to make the release.
The permissions are now fixed (also for govuk_template_ejs) and the CI job was re-run.
